# Generated by Django 3.2.5 on 2021-08-17 18:40

from django.db import migrations, models
import owner.models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=owner.models.logofile),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=owner.models.logofile),
        ),
    ]
